### PR TITLE
SWIM flag

### PR DESCRIPTION
**Pull request by igroglaz**
Added SWIM flag based on FEATHER flag:
1) in display-ui.c I moved swimming to the bottom, so it won't ruin existing order of stuff in resistance's panel
2) I didn't add it to randarts generation, so not to disturb balance

### CODE REVIEW

**Comment by igroglaz** [comment]
tested on localhost with Ent - works alight

**Comment by draconisPW** [comment]
This should not be an object flag, but a player flag (goes into the # menu with race/class abilities).

**Comment by igroglaz** [comment]
> This should not be an object flag, but a player flag (goes into the # menu with race/class abilities).

it's already in # menu with race/class abilities. When I've tested it on Ent - it was shown at character creation screen.

**Comment by igroglaz** [comment]
The good thing about obj flag - that it gives more opportunities on game balancing.. as I excluded it from randarts generation - this flag do not influence game balance. But at the same time it allows some interesting possibilities, eg rebalance of rarity (and usefulness) of FEATHER flag (make it more rare) while make more common SWIM and assigning it to some interesting items.

**Pull request closed without merging**
