### PR TITLE
support ttf font

### PR DESCRIPTION
**Pull request by s88100**
reloads tiles real-time in game. AcceptChanges() (do_update_f) for font and (do_update_w) - for windows[i].

### CODE REVIEW

**Comment by draconisPW** [comment]
I compiled the client, tried to change font size using the button, but this instantly crashes for me...

**Comment by draconisPW** [comment]
Line 1512:

string_free(window->req_font);
window->req_font = string_make(window->req_font);

This makes no sense at all...

**Comment by draconisPW** [comment]
There's clearly a part missing that should map a font to a font size.

**Comment by s88100** [comment]
checked Borland C++ Builder 6 it seems the font doesn't need to be reloaded

in AcceptChanges()
...

```
if (do_update_f)
    {
        ResizeWin(&windows[SelectedTerm], windows[SelectedTerm].width, windows[SelectedTerm].height);

        /* Show on the screen */
        sdl_BlitAll();
    }
```

**Pull request merged**
